### PR TITLE
Make sample_rate a required arg and add do_resample arg

### PR DESCRIPTION
**Pull request by jonashaag**
Refs https://github.com/mpariente/asteroid/pull/189

### CODE REVIEW

**Comment by mpariente** [comment]
Thanks ! I kept the `do_resample` because I didn't test enough without the resampling, even if it should be similar.. Have you tried?

**Comment by jonashaag** [comment]
I don’t think it gives useful results with resample=False. But from a code point of view, it doesn’t make sense to have a conditional always be True. So probably best to remove the flag entirely

**Comment by mpariente** [comment]
IDK, I tried to scale the constants according to the sampling rate, it might work. 
I'd like to keep the flag (which doesn't make sense) until I experiment with it.

**Comment by jonashaag** [comment]
I'm sure it can be generalized to other sample rates, I just meant it doesn't give useful results if you just put in audio in X != 10 kHz in the 10kHz mode :)

**Comment by jonashaag** [comment]
Although interestingly, I got some acceptable results for the lower frequencies using it as a loss for 8kHz audio... but then I've also not looked at the STOI definition en dé­tail so maybe that's expected

**Pull request merged**
